### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kerrtravers** [liam4/liam4.github.io#1]
This is pretty old, but I plan on change my site URL next month, could I use a bit of this code with credit?

**Comment by towerofnix** [comment]
Go ahead! Give credits if you want, but it's not really necessary; the extent of the code is this:

```js
const url = (
  'https://towerofnix.github.io' + location.pathname + location.hash
)
location.replace(url)
document.getElementById('link').href = url
```

And I hereby decree that that snippet of code is under public domain :P

**Comment by kerrtravers** [comment]
Thanks 👍🏻

**Comment by joker314** [comment]
@ktrvs but the code has now been improved-- so you may want to update yours too

**Comment by kerrtravers** [comment]
@joker314 I'll probably end up leaving it as it is, the old domain that I'm redirecting from is expiring soon anyway.
